from .models.JerarquiaAcad import JerarquiaAcad
from .models.Institucion import Institucion
from .models.Facultad import Facultad
from .models.Escuela import Escuela
from .models.Carrera import Carrera
from .models.NaturalPerson import NaturalPerson
from skyend_configs.models.UnidadMedida import UnidadMedida
from skyend_configs.models.Contrato import Contrato
from skyend_configs.models.Documento import Documento
from .models.Contrato import Contrato
from .models.Documento import Documento